# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
  - package-ecosystem: 'npm'
    directory: '/npm'
    schedule:
      interval: 'daily'
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
  - package-ecosystem: 'npm'
    directory: '/internal-ui'
    schedule:
      interval: 'daily'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
