name: deploy
on:
  push:
    branches:
      - main
concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
  packages: write

jobs:
    deploy:
      name: Deploy Application
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v3

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

        - name: Build image
          run: docker build --platform linux/amd64 -t boxyhq/jackson:latest .

        - name: Tag image
          run: docker tag boxyhq/jackson:latest registry.digitalocean.com/auditive/auditive-sso:latest

        - name: Log in to DO Container Registry
          run: doctl registry login --expiry-seconds 1200

        - name: Push image
          run: docker push registry.digitalocean.com/auditive/auditive-sso:latest
